<?php
/*
This file was autogenerated by ConfigurationLoader.class.php.
Please do not attempt to alter it's contents manually as any changes you make may be overwritten
*/
class ns
{
function __construct()
{
$this->db = new ns_db();
$this->plm = new ns_plm();
$this->param = new ns_param();

}
}
class ns_db
{
function __construct()
{
$this->loop = new ns_db_loop();
$this->online = new ns_db_online();

}
}
class ns_db_loop
{
public $host;
public $username;
public $password;
public $dbname;
public $port;
function __construct()
{
$this->host = (string) "localhost";
$this->username = (string) "root";
$this->password =  null;
$this->dbname = (string) "nsid_plm_data";
$this->port =  3306;

}
}
class ns_db_online
{
public $host;
public $username;
public $password;
public $dbname;
public $port;
function __construct()
{
$this->host = (string) "localhost";
$this->username = (string) "gkrip_dbuser";
$this->password = (string) "ns00.6-reader";
$this->dbname = (string) "gkriptorg_nsid_plm_data";
$this->port =  3306;

}
}
class ns_plm
{
public $title;
public $debug;
public $version;
public $status;
function __construct()
{
$this->title = (string) "NS-PLM";
$this->debug = (int) 0;
$this->version = (string) "00.3";
$this->status = (string) "dev";

}
}
class ns_param
{
function __construct()
{
$this->search = new ns_param_search();
$this->user = new ns_param_user();

}
}
class ns_param_search
{
public $history;
function __construct()
{
$this->history = (int) 10;

}
}
class ns_param_user
{
public $md5_passw;
public $auth_debug;
public $guest_allowed;
function __construct()
{
$this->md5_passw = (int) 0;
$this->auth_debug = (int) 0;
$this->guest_allowed = (int) 1	;

}
}
?>