<?php
/*
This file was autogenerated by ConfigurationLoader.class.php.
Please do not attempt to alter it's contents manually as any changes you make may be overwritten
*/
class ns
{
function __construct()
{
$this->db = new ns_db();
$this->plm = new ns_plm();
$this->param = new ns_param();

}
}
class ns_db
{
function __construct()
{
$this->loop = new ns_db_loop();
$this->online = new ns_db_online();

}
}
class ns_db_loop
{
public $host;
public $username;
public $password;
public $dbname;
public $port;
function __construct()
{
$this->host = (string) "localhost";
$this->username = (string) "root";
$this->password =  null;
$this->dbname = (string) "nsid_plm_data";
$this->port =  3306;

}
}
class ns_db_online
{
public $host;
public $username;
public $password;
public $dbname;
public $port;
function __construct()
{
$this->host = (string) "localhost";
$this->username = (string) "gkrip_dbuser";
$this->password = (string) "ns00.6-reader";
$this->dbname = (string) "gkriptorg_nsid_plm_data";
$this->port =  3306;

}
}
class ns_plm
{
public $title;
public $debug;
public $version;
public $status;
function __construct()
{
$this->title = (string) "Coelme NS-PLM";
$this->debug = (int) 0;
$this->version = (string) "00.3-6";
$this->status = (string) "d";
$this->modules = new ns_plm_modules();

}
}
class ns_plm_modules
{
public $warehouse;
public $providers;
public $movements;
public $inventory;
public $traceability;
function __construct()
{
$this->warehouse = (int) 0;
$this->providers = (int) 0;
$this->movements = (int) 0;
$this->inventory = (int) 0;
$this->traceability = (int) 0;

}
}
class ns_param
{
public $redirect_time;
public $timezone;
function __construct()
{
$this->redirect_time = (int) 5;
$this->timezone = (string) "Europe/Rome";
$this->search = new ns_param_search();
$this->user = new ns_param_user();
$this->company = new ns_param_company();

}
}
class ns_param_search
{
public $history;
function __construct()
{
$this->history = (int) 10;

}
}
class ns_param_user
{
public $md5_passw;
public $auth_debug;
public $guest_allowed;
function __construct()
{
$this->md5_passw = (int) 0;
$this->auth_debug = (int) 0;
$this->guest_allowed = (int) 0;

}
}
class ns_param_company
{
public $logo;
public $image;
public $heigth;
public $link;
public $target;
function __construct()
{
$this->logo = (int) 1;
$this->image = (string) "nsid.png";
$this->heigth = (string) "300px";
$this->link = (string) "index.php";
$this->target =  null;

}
}
?>